In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
import seaborn as sns

In [2]:
dataset= np.array([[2.7810836,2.550537003],[1.465489372,2.362125076]])
coef = np.array([-0.406605464, 0.852573316, -1.104746259])
params = np.array([0, 0, 0])
y = np.array([0,0])

In [3]:
def sigmoid(X, weight):
    z = np.dot(X, weight)
    return 1 / (1 + np.exp(-z))

In [4]:
def loss(h, y):
    return (-y * np.log(h) - (1 - y) * np.log(1 - h)).mean()

In [5]:
def gradient_descent(X, h, y):
    return np.dot(X.T, (h - y)) / y.shape[0]
def update_weight_loss(weight, learning_rate, gradient):
    return weight - learning_rate * gradient

In [6]:
X = dataset
y = y
num_iter = 100000
intercept = np.ones((X.shape[0], 1))
X = np.concatenate((intercept, X), axis=1)
theta = np.zeros(X.shape[1])
for i in range(num_iter):
    h = sigmoid(X, theta)
    gradient = gradient_descent(X, h, y)
    theta = update_weight_loss(theta, 0.1, gradient)
print(theta)
result = sigmoid(X, theta)
print(result)

[-1.16895967 -2.01885295 -2.80501745]
[8.84838939e-07 2.13728175e-05]


In [7]:
X = datasets.load_iris

In [8]:
data = np.loadtxt('university_Admissions.txt', delimiter=",")

In [9]:
x = data[:, 0:2]
y = data[:, 2]

In [10]:
print(data[:5])

[[34.62 78.02  0.  ]
 [30.29 43.89  0.  ]
 [35.85 72.9   0.  ]
 [60.18 86.31  1.  ]
 [79.03 75.34  1.  ]]


In [11]:
X = x
y = y
num_iter = 100000
intercept = np.ones((X.shape[0], 1))
X = np.concatenate((intercept, X), axis=1)
theta = np.zeros(X.shape[1])
for i in range(num_iter):
    h = sigmoid(X, theta)
    gradient = gradient_descent(X, h, y)
    theta = update_weight_loss(theta, 0.01, gradient)
print(theta)
result = sigmoid(X, theta)
print(np.round(result,2))

[-9.0911091   4.98877706 -3.32151746]
[0.   0.02 0.   0.99 1.  ]


In [12]:
def compute_theta(X, y, theta):
    for i in range(num_iter):
        h = sigmoid(X, theta)
        gradient = gradient_descent(X, h, y)
        theta = update_weight_loss(theta, 0.1, gradient)
    #print(theta)
    return(theta)
    #theta = update_weight_loss(theta, 0.1, gradient_descent(X, sigmoid(X, theta), y)) for i in range(num_iter)

In [13]:
def transform_x(X):    
    intercept = np.ones((X.shape[0], 1))
    X = np.concatenate((intercept, X), axis=1)
    return(X)

In [14]:
X = x
y = y
num_iter = 100000
X = transform_x(X)
int_theta = np.zeros(X.shape[1])
theta = compute_theta(X, y, int_theta)
result = sigmoid(X, theta)
print(np.round(result,2))

[0. 0. 0. 1. 1.]


In [15]:
def ova(X, y):
    X = transform_x(X)
    
    num_observations = X.shape[0]
    num_features = X.shape[1]
    labels = np.unique(y)
    num_labels = np.shape(np.unique(y))[0] 
    
    classifiers = np.zeros(shape=(num_labels, num_features))
        
    dict_label = {}
    for i in range(num_labels):
        dict_label[i] = labels[i]
        label = (y == labels[i]).astype(int)
        #print(label)
        int_theta = np.zeros(X.shape[1])
        classifiers[i, :] = compute_theta(X, label, int_theta)
        
    result = sigmoid(X, classifiers.transpose())
    predictions = result.argmax(axis=1)  
    y_pred = np.array([dict_label[i] for i in predictions])
    #return result, dict_label, predictions
    return y_pred, classifiers, dict_label
        

In [16]:
X = x
y = y
num_iter = 100000
X = transform_x(X)
int_theta = np.zeros(X.shape[1])
result = ova(X, y)
print(result)

(array([0., 0., 0., 1., 1.]), array([[ 41.72386103,  41.72386103, -25.98243347,  16.38296468],
       [-41.72386103, -41.72386103,  25.98243347, -16.38296468]]), {0: 0.0, 1: 1.0})


In [17]:
data = datasets.load_iris()
X = data['data']
y = data['target']
num_iter = 100000
X = transform_x(X)
int_theta = np.zeros(X.shape[1])
y_pred = ova(X, y)
#print(result[2])
print(y_pred)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]), array([[  0.66188151,   0.66188151,   1.01745045,   3.81018116,
         -6.06645969,  -2.87497669],
       [  3.68924327,   3.68924327,  -0.24535671,  -2.79656809,
          1.31364331,  -2.77834391],
       [-10.35906919, -10.35906919,  -3.172289  ,  -5.01690089,
          7.07583322,  11.96281996]]), {0: 0, 1: 1, 2: 2})


In [ ]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y, y_pred))


In [19]:
import pandas as pd
import numpy as np
from sklearn import tree, model_selection, metrics, tree, naive_bayes, svm, neural_network 
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score

In [20]:
col_name = ['sample_id', 'length', 'width', 'thickness', 'surface_area', 
                  'mass', 'compactness', 'hardness', 'shell_top_radius', 'water_content', 
                  'carbohydrate_content', 'variety']
df = pd.read_csv('2602567.txt', sep='\t', header=None )
new_df = df.transpose()
new_df.columns = col_name
new_df.set_index(['sample_id'])

features_x = new_df.loc[ :, 'length':'carbohydrate_content']
target_y = new_df.loc[ :, 'variety']
features_x = features_x.astype(float)
X_train, X_test, y_train, y_test = model_selection.train_test_split(features_x, target_y, test_size=0.3)


In [21]:
X = X_train
y = y_train
num_iter = 100000
int_theta = np.zeros(X.shape[1])
result = ova(X, y)
#print(result[2])
print(result[0])

['c_cornuta' 'c_cornuta' 'c_americana' 'c_avellana' 'c_americana'
 'c_cornuta' 'c_americana' 'c_cornuta' 'c_americana' 'c_americana'
 'c_cornuta' 'c_americana' 'c_avellana' 'c_cornuta' 'c_americana'
 'c_avellana' 'c_americana' 'c_americana' 'c_americana' 'c_cornuta'
 'c_cornuta' 'c_americana' 'c_cornuta' 'c_cornuta' 'c_cornuta' 'c_cornuta'
 'c_avellana' 'c_avellana' 'c_cornuta' 'c_americana' 'c_avellana'
 'c_cornuta' 'c_cornuta' 'c_cornuta' 'c_avellana' 'c_americana'
 'c_americana' 'c_americana' 'c_avellana' 'c_cornuta' 'c_americana'
 'c_avellana' 'c_americana' 'c_avellana' 'c_americana' 'c_cornuta'
 'c_americana' 'c_americana' 'c_americana' 'c_americana' 'c_cornuta'
 'c_cornuta' 'c_avellana' 'c_avellana' 'c_americana' 'c_cornuta'
 'c_cornuta' 'c_americana' 'c_americana' 'c_americana' 'c_americana'
 'c_avellana' 'c_cornuta' 'c_americana' 'c_avellana' 'c_americana'
 'c_americana' 'c_cornuta' 'c_cornuta' 'c_cornuta' 'c_americana'
 'c_cornuta' 'c_americana' 'c_avellana' 'c_americana' 'c_a

In [22]:
print(accuracy_score(y, result[0]))

0.8285714285714286


In [23]:
print(result)

(array(['c_cornuta', 'c_cornuta', 'c_americana', 'c_avellana',
       'c_americana', 'c_cornuta', 'c_americana', 'c_cornuta',
       'c_americana', 'c_americana', 'c_cornuta', 'c_americana',
       'c_avellana', 'c_cornuta', 'c_americana', 'c_avellana',
       'c_americana', 'c_americana', 'c_americana', 'c_cornuta',
       'c_cornuta', 'c_americana', 'c_cornuta', 'c_cornuta', 'c_cornuta',
       'c_cornuta', 'c_avellana', 'c_avellana', 'c_cornuta',
       'c_americana', 'c_avellana', 'c_cornuta', 'c_cornuta', 'c_cornuta',
       'c_avellana', 'c_americana', 'c_americana', 'c_americana',
       'c_avellana', 'c_cornuta', 'c_americana', 'c_avellana',
       'c_americana', 'c_avellana', 'c_americana', 'c_cornuta',
       'c_americana', 'c_americana', 'c_americana', 'c_americana',
       'c_cornuta', 'c_cornuta', 'c_avellana', 'c_avellana',
       'c_americana', 'c_cornuta', 'c_cornuta', 'c_americana',
       'c_americana', 'c_americana', 'c_americana', 'c_avellana',
       'c_cornuta', '

In [24]:
print(transform_x(X_test).shape)
print(y_test.shape)
print(result[1].shape)
#print()
y_result = sigmoid(transform_x(X_test), result[1].transpose())
predictions = y_result.argmax(axis=1)  
y_pred = np.array([result[2][i] for i in predictions])
print(y_test)
print(accuracy_score(y_test, y_pred))


(61, 11)
(61,)
(3, 11)
177      c_cornuta
152     c_avellana
138     c_avellana
165      c_cornuta
10       c_cornuta
120     c_avellana
96     c_americana
150     c_avellana
8      c_americana
157     c_avellana
43       c_cornuta
178    c_americana
102    c_americana
87     c_americana
53      c_avellana
94     c_americana
117     c_avellana
158     c_avellana
118     c_avellana
184    c_americana
116    c_americana
74      c_avellana
137      c_cornuta
181      c_cornuta
72       c_cornuta
99      c_avellana
171     c_avellana
13     c_americana
148      c_cornuta
168     c_avellana
          ...     
108      c_cornuta
186    c_americana
5        c_cornuta
85     c_americana
4      c_americana
124      c_cornuta
14       c_cornuta
27     c_americana
109    c_americana
163    c_americana
22     c_americana
0       c_avellana
159    c_americana
131     c_avellana
129    c_americana
128      c_cornuta
127    c_americana
134      c_cornuta
30     c_americana
76       c_cornuta
125    c

In [ ]:
#import random
#print(new_df.head(5))
for i in range(2):
    shuf_df = new_df.sample(frac=1).reset_index(drop=True)
    #print(shuf_df.head(5))
    
    
    features_x = new_df.loc[ :, 'length':'carbohydrate_content']
    target_y = new_df.loc[ :, 'variety']
    features_x = features_x.astype(float)
    X_train, X_test, y_train, y_test = model_selection.train_test_split(features_x, target_y, test_size=0.3)
        
    X = X_train
    y = y_train
    num_iter = 100000
    int_theta = np.zeros(X.shape[1])
    result = ova(X, y)
    
    print("\nTrain ", i," Result")
    print(accuracy_score(y, result[0]))
    
    test_result = sigmoid(transform_x(X_test), result[1].transpose())
    test_predictions = test_result.argmax(axis=1)  
    y_pred = np.array([result[2][i] for i in test_predictions])
    
    print("\nTest ", i, " Result")
    print(accuracy_score(y_test, y_pred))
    
    